// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApi.Data;

namespace webApi.Migrations
{
    [DbContext(typeof(CrveniKrstContext))]
    partial class CrveniKrstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("webApi.Models.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("webApi.Models.Tim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBrojVolontera")
                        .HasColumnType("int");

                    b.Property<int?>("MojGradId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MojGradId");

                    b.ToTable("Timovi");
                });

            modelBuilder.Entity("webApi.Models.Volonter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MojGradId")
                        .HasColumnType("int");

                    b.Property<int?>("MojTimId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MojGradId");

                    b.HasIndex("MojTimId");

                    b.ToTable("Volonteri");
                });

            modelBuilder.Entity("webApi.Models.Tim", b =>
                {
                    b.HasOne("webApi.Models.Grad", "MojGrad")
                        .WithMany("NizTimova")
                        .HasForeignKey("MojGradId");

                    b.Navigation("MojGrad");
                });

            modelBuilder.Entity("webApi.Models.Volonter", b =>
                {
                    b.HasOne("webApi.Models.Grad", "MojGrad")
                        .WithMany("NizVolontera")
                        .HasForeignKey("MojGradId");

                    b.HasOne("webApi.Models.Tim", "MojTim")
                        .WithMany("NizVolontera")
                        .HasForeignKey("MojTimId");

                    b.Navigation("MojGrad");

                    b.Navigation("MojTim");
                });

            modelBuilder.Entity("webApi.Models.Grad", b =>
                {
                    b.Navigation("NizTimova");

                    b.Navigation("NizVolontera");
                });

            modelBuilder.Entity("webApi.Models.Tim", b =>
                {
                    b.Navigation("NizVolontera");
                });
#pragma warning restore 612, 618
        }
    }
}
